/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DubboConfiguration.java
 *
 * Created on 2019-5-27, 16:48:45
 */
package view;

import com.alibaba.dubbo.common.utils.StringUtils;
import model.Config;
import service.ConfigService;
import tools.PropertyTools;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.IOException;

/**
 *
 * @author DELL
 */
public class ConfigurationFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 292013292618471581L;
	private DubboTestFrame baseFrame = null;
	
	/** Creates new form DubboConfiguration */
	public ConfigurationFrame(DubboTestFrame baseFrame) {
		initComponents();
		this.baseFrame = baseFrame;
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();

		setName("Form"); // NOI18N
		setTitle("DUBBO 接口测试配置");

		Font font = new Font(Font.DIALOG, Font.PLAIN, 16);
		this.setTextFieldFont();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
				"Dubbo Interface Setting", 0, 0, font)); // NOI18N
		jPanel1.setName("jPanel1"); // NOI18N

		jLabel1.setFont(font); // NOI18N
		jLabel1.setText("ZooKeeper:"); // NOI18N
		jLabel1.setName("jLabel1"); // NOI18N

		jTextField1.setText(""); // NOI18N
		jTextField1.setName("jTextField1"); // NOI18N

		jButton1.setFont(font); // NOI18N
		jButton1.setText("TEST"); // NOI18N
		jButton1.setName("jButton1"); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setFont(font); // NOI18N
		jLabel2.setText("Application:"); // NOI18N
		jLabel2.setName("jLabel2"); // NOI18N

		jTextField2.setText(""); // NOI18N
		jTextField2.setName("jTextField2"); // NOI18N

		jLabel3.setFont(font); // NOI18N
		jLabel3.setText("Interface:"); // NOI18N
		jLabel3.setName("jLabel3"); // NOI18N

		jTextField3.setText(""); // NOI18N
		jTextField3.setName("jTextField3"); // NOI18N

		jLabel4.setFont(font); // NOI18N
		jLabel4.setText("MethodName:"); // NOI18N
		jLabel4.setName("jLabel4"); // NOI18N

		jTextField4.setName("jTextField4"); // NOI18N

		jLabel5.setFont(font); // NOI18N
		jLabel5.setText("Version:"); // NOI18N
		jLabel5.setName("jLabel5"); // NOI18N

		jTextField5.setName("jTextField5"); // NOI18N

		jLabel6.setFont(font); // NOI18N
		jLabel6.setText("Group:"); // NOI18N
		jLabel6.setName("jLabel6"); // NOI18N

		jTextField6.setName("jTextField6"); // NOI18N

		jTextField7.setName("jTextField7"); // NOI18N
		
		this.setTextFieldValue();

		jLabel7.setFont(font); // NOI18N
		jLabel7.setText("RequestClass:"); // NOI18N
		jLabel7.setName("jLabel7"); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel2).addComponent(jLabel1)
																.addComponent(jLabel3).addComponent(jLabel4))
														.addGap(18, 18, 18)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField4,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 716,
																		Short.MAX_VALUE)
																.addComponent(jTextField3,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 716,
																		Short.MAX_VALUE)
																.addComponent(jTextField1,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 716,
																		Short.MAX_VALUE)
																.addComponent(jTextField2,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 716,
																		Short.MAX_VALUE))
														.addGap(18, 18, 18).addComponent(jButton1).addContainerGap())
										.addGroup(
												jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel7).addComponent(jLabel5)
																.addComponent(jLabel6))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField6,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 716,
																		Short.MAX_VALUE)
																.addComponent(jTextField5,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 716,
																		Short.MAX_VALUE)
																.addComponent(jTextField7,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 716,
																		Short.MAX_VALUE))
														.addGap(99, 99, 99)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jButton1).addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel7).addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));


		jButton2.setFont(font); // NOI18N
		jButton2.setText("Apply"); // NOI18N
		
		jButton2.setName("jButton2"); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setFont(font); // NOI18N
		jButton3.setText("Save"); // NOI18N
		jButton3.setName("jButton3"); // NOI18N
		jButton3.setMnemonic(KeyEvent.VK_1); 
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setFont(font); // NOI18N
		jButton4.setText("Cancel"); // NOI18N
		jButton4.setName("jButton4"); // NOI18N
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(695, Short.MAX_VALUE).addComponent(jButton2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton3).addGap(14, 14, 14).addComponent(jButton4).addContainerGap())
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton4).addComponent(jButton3).addComponent(jButton2))
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		ConfigService configService = new ConfigService();
		String zookeeper = StringUtils.isNotEmpty(jTextField1.getText()) ? jTextField1.getText().trim() : "";
		boolean isConnenct = configService.checkZooKeeper(zookeeper);
		if(isConnenct){
			JOptionPane.showMessageDialog(null, " SUCCESS !!!");
		} else {
			JOptionPane.showMessageDialog(null, "Connection test failed!!!\nPlease check the zooKeeper URL address.\ne.g. "
					+ " zookeeper://172.19.42.66:2181");
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		this.saveTextFiledValue();
		baseFrame.setUrl();
		jButton2.setEnabled(false);
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		this.saveTextFiledValue();
		baseFrame.setUrl();
		dispose();
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		dispose();
	}// GEN-LAST:event_jButton4ActionPerformed
	
	/**
	 * 设置文本框的font
	 */
	private void setTextFieldFont(){
		Font font = new Font(Font.DIALOG, Font.BOLD, 16);
		jTextField1.setFont(font);
		jTextField2.setFont(font);
		jTextField3.setFont(font);
		jTextField4.setFont(font);
		jTextField5.setFont(font);
		jTextField6.setFont(font);
		jTextField7.setFont(font);
	}
	
	/**
	 * 设置文本数值
	 */
	private void setTextFieldValue(){
		Config config = new Config();
		try{
			config = PropertyTools.getConfig();
		} catch (IOException ex){
			ex.printStackTrace();
			JOptionPane.showMessageDialog(null, "读取配置文件失败");
		}
		jTextField1.setText(config.getZooKeeper());
		jTextField2.setText(config.getApplication());
		jTextField3.setText(config.getInterfaze());
		jTextField4.setText(config.getMethodName());
		jTextField5.setText(config.getVersion());
		jTextField6.setText(config.getGroup());
		jTextField7.setText(config.getRequestClass());
	}
	
	/**
	 * 写入配置文件
	 */
	private void saveTextFiledValue(){
		Config config = new Config();
		String zookeeper = StringUtils.isNotEmpty(jTextField1.getText()) ? jTextField1.getText().trim() : "";
		String application = StringUtils.isNotEmpty(jTextField2.getText()) ? jTextField2.getText().trim() : "";
		String interfaze = StringUtils.isNotEmpty(jTextField3.getText()) ? jTextField3.getText().trim() : "";
		String methodName =StringUtils.isNotEmpty(jTextField4.getText()) ? jTextField4.getText().trim() : "";
		String version =StringUtils.isNotEmpty(jTextField5.getText()) ? jTextField5.getText().trim() : "";
		String group =StringUtils.isNotEmpty(jTextField6.getText()) ? jTextField6.getText().trim() : "";
		String requestClass =StringUtils.isNotEmpty(jTextField7.getText()) ? jTextField7.getText().trim() : "";
		config.setZooKeeper(zookeeper).setApplication(application).setInterfaze(interfaze).setMethodName(methodName)
		.setVersion(version).setRequestClass(requestClass).setGroup(group);
		try {
			PropertyTools.writeConfig(config);
		} catch (IOException e) {
			JOptionPane.showMessageDialog(null, "写入配置文件失败");
		}
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	// End of variables declaration//GEN-END:variables
}
