/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DubboTestFrame.java
 *
 * Created on 2019-5-27, 15:30:00
 */
package view;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;
import model.Config;
import service.DubboTestService;
import tools.ExceptionTools;
import tools.PropertyTools;
import tools.StringUtils;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

/**
 *
 * @author DELL
 */
public class DubboTestFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8742493268193832033L;

	/** Creates new form DubboTestFrame */
	public DubboTestFrame() {
		initComponents();
		setLocationRelativeTo(null);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jSeparator1 = new javax.swing.JSeparator();
		jPanel5 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jPanel3 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem2 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setName("Form"); // NOI18N
		setTitle("DUBBO 接口测试");

		Font font = new Font(Font.DIALOG, Font.PLAIN, 16);
		Font userInputFont = new Font(Font.DIALOG, Font.BOLD, 16);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
				"Dubbo Interface", 0, 0, font)); // NOI18N
		jPanel1.setName("jPanel1"); // NOI18N

		jTextField1.setText(""); // NOI18N
		jTextField1.setName("jTextField1"); // NOI18N
		jTextField1.setFont(userInputFont);
		jButton1.setFont(font); // NOI18N
		jButton1.setText("GO"); // NOI18N
		jButton1.setName("jButton1"); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createSequentialGroup().addContainerGap()
										.addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 991,
												Short.MAX_VALUE)
										.addGap(18, 18, 18).addComponent(jButton1).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton1))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
		jTabbedPane1.setFont(new Font("Dialog", 1, 14)); // NOI18N
		jTabbedPane1.setName("jTabbedPane1"); // NOI18N

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel2.setName("jPanel2"); // NOI18N

		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Request JSON data：", 0, 0, font)); // NOI18N
		jPanel4.setName("jPanel4"); // NOI18N

		jScrollPane1.setName("jScrollPane1"); // NOI18N

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setName("jTextArea1"); // NOI18N
		jTextArea1.setFont(userInputFont);
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE));

		jSeparator1.setName("jSeparator1"); // NOI18N

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Response JSON data：", 0, 0, font)); // NOI18N
		jPanel5.setName("jPanel5"); // NOI18N

		jScrollPane2.setName("jScrollPane2"); // NOI18N

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jTextArea2.setName("jTextArea2"); // NOI18N
		jTextArea2.setFont(userInputFont);
		jScrollPane2.setViewportView(jTextArea2);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
				.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel5,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("Single Request Param Interface Test", jPanel2); // NOI18N

		jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel3.setName("jPanel3"); // NOI18N

		jLabel2.setText("暂时未实现"); // NOI18N
		jLabel2.setName("jLabel2"); // NOI18N

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(jLabel2)
						.addContainerGap(1004, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(jLabel2)
						.addContainerGap(751, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Multiple Request Params Interface Test", jPanel3); // NOI18N

		jMenuBar1.setName("jMenuBar1"); // NOI18N

		jMenu1.setText("开始"); // NOI18N
		jMenu1.setName("jMenu1"); // NOI18N
		jMenu1.setFont(font);

		jMenuItem1.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
		jMenuItem1.setText("版本信息"); // NOI18N
		jMenuItem1.setName("jMenuItem1"); // NOI18N
		jMenuItem1.setFont(font);
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem3.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
		jMenuItem3.setText("关闭"); // NOI18N
		jMenuItem3.setName("jMenuItem3"); // NOI18N
		jMenuItem3.setFont(font);
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("编辑"); // NOI18N
		jMenu2.setName("jMenu2"); // NOI18N
		jMenu2.setFont(font);
		jMenuItem2.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
		jMenuItem2.setText("环境设置"); // NOI18N
		jMenuItem2.setName("jMenuItem2"); // NOI18N
		jMenuItem2.setFont(font);
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem2);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
						.addContainerGap()));
		pack();
		this.setUrl();
		this.setUserRequest();
	}// </editor-fold>//GEN-END:initComponents

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		// TODO add your handling code here:
		new ConfigurationFrame(this).setVisible(true);
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		// TODO add your handling code here:
		JOptionPane.showMessageDialog(null, "Version: 1.0.0 \nContact: chi.zhang@weimob.com");
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		// TODO add your handling code here:
		dispose();
		System.exit(0);
	}// GEN-LAST:event_jMenuItem3ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		DubboTestService testService = new DubboTestService();
		String requestParams = jTextArea1.getText();
		Object response = "";
		try {
			PropertyTools.writeUserParam(requestParams);
			response = testService.getResponse(PropertyTools.getConfig(), requestParams);
			jTextArea2.setText(JSON.toJSONString(response, SerializerFeature.PrettyFormat));
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "调用发生异常，详细请查看日志。");
			jTextArea2.setText(ExceptionTools.getStackTrace(e));
		}
	
	}// GEN-LAST:event_jButton1ActionPerformed

	public void setUrl(){
		Config config = new Config();
		try {
			config = PropertyTools.getConfig();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(this, "读取配置文件失败");
		}
		jTextField1.setEditable(false);
		String zookeeper = config.getZooKeeper();
		String application = config.getApplication();
		String interfaze = config.getInterfaze();
		String methodName = config.getMethodName();
		String requestClass = config.getRequestClass();
		String version = config.getVersion();
		String group = config.getGroup();
		if(StringUtils.isEmpty(zookeeper)) return;
		StringBuilder urlBuilder = new StringBuilder(zookeeper).append("?application=")
				.append(application).append("&interface=").append(interfaze).append("&methodName=")
				.append(methodName);
		if(StringUtils.isNotEmpty(requestClass)){
			urlBuilder.append("&requestClass=").append(requestClass);
		}
		if(StringUtils.isNotEmpty(version)){
			urlBuilder.append("&version=").append(version);
		}
		if(StringUtils.isNotEmpty(group)){
			urlBuilder.append("&group=").append(group);
		}
		jTextField1.setText(urlBuilder.toString());
	}
	
	private void setUserRequest(){
		try {
			String request = PropertyTools.getUserParam();
			jTextArea1.setText(request);
		} catch (IOException e) {
			JOptionPane.showMessageDialog(null, "用户历史请求参数读取失败。");
		}
		
	}
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String []args) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DubboTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DubboTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DubboTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DubboTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new DubboTestFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}
